### ISSUE TITLE
Errors on start up.

### ISSUE THREAD

**Issue by OhTanoshi** [DamienTehDemon/Damiens-Roleplay-Project#6]
There seems to maybe be missing files etc. 
That's just what i can gather from what little testing i did.

anyways. from what i can tell its pretty creative stuff you've got in there.

if possible i would like to get a working version so i can build off it so i don't have to look through all the code and figure out all your code specifically .

if you don't want to give out a working version then i completely understand from the amount of leechers around in fivem

**Comment by OhTanoshi** [comment]
Upon further testing. its due to database not connecting. could actually be my MySQL server refusing connections again but not 100% yet

**Comment by OhTanoshi** [comment]
I've manager to fix all the errors i had. was just missing files. now im running into sql tables missing. Wondering if you could possibly share those if you have them

**Comment by OhTanoshi** [comment]
You can add me or message me on discord at Tanoshi#3910

**Comment by D4M13N-D3V** [comment]
https://drive.google.com/open?id=1WGyrT-L_vjLARxkdEabAFyyYafbyfbsV -sql import

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by OhTanoshi** [comment]
Thanks! lol sat last night manually making the database to do some debugging took for ever.
